package pl.com.schoolsystem.teacher;

public enum TeacherSpecialization {
  ART,
  BIOLOGY,
  BUSINESS_STUDIES,
  CHEMISTRY,
  ENGLISH,
  POLISH,
  FOREIGN_LANGUAGES,
  GEOGRAPHY,
  HISTORY,
  HUMANITIES,
  INFORMATION_TECHNOLOGY,
  MATHEMATICS,
  MUSIC,
  NATURAL_SCIENCES,
  PHYSICAL_EDUCATION,
  PHYSIC,
  TECHNOLOGY
}
